### ISSUE TITLE
Add hiema roekwurst

### ISSUE THREAD

**Issue by arte921** [FeestCoders/Creeperlist-Front-End#4]

**Comment by BennovanDorst** [comment]
jij idioot ik had meer van jouw verwacht nu je bek houden

**Comment by arte921** [comment]
Nee

**Comment by arte921** [comment]
Ga hiama rookwuest command maken

**Comment by BennovanDorst** [comment]
Ja als je hiema roekwurst command wil contribute [hier](https://github.com/FeestCoders/discord-bot)

**Comment by arte921** [comment]
[Ik heb nog een open source minecraft server listing gevonden](https://youtu.be/dQw4w9WgXcQ)
